### ISSUE TITLE
How to run it?

### ISSUE THREAD

**Issue by petmolot** [upsuper/migrate-itunes-to-rhythmbox#1]
Thank you for writing this. It is maybe not an 'issue', but could you explain the basics of how to run the tool in the readme, for someone who is not familiar with cargo/rust?

**Comment by upsuper** [comment]
This is already documented in https://github.com/upsuper/migrate-itunes-to-rhythmbox#usage

Please let me know if there is anything unclear.

**Comment by petmolot** [comment]
Thanks for the quick reply! I had to run some cargo commands to compile the tool, before running it, and  look for the executable file in a subfolder. It may be helpful to some users to mention these steps (unless it is obvious, but it wasn't for me). Anyway I managed, but the script sadly gave an error i couldnt figure out (on itunes 12.12.7.1. I used something else in python in the end. but thank you anyway!
